window.GROWTH_ENGINE_DATA = {
  "lastUpdated": "2026-08-20",
  "totalPins": 30,
  "totalImpressions": 0,
  "totalSaves": 0,
  "totalOutboundClicks": 0,
  "averageCtr": 0.0,
  "referralClicks": 0,
  "isDemoData": false,
  "topCategory": "Pokemon",
  "topHook": "What Happens When a Live Auction Starts at $1?",
  "topTemplate": "Template B (Bold Typography)",
  "pins": [
    {
      "pin_id": "PIN-01",
      "filename": "pin-01-pokemon.png",
      "category": "pokemon",
      "template": "A",
      "headline": "Pok\u00e9mon Cards You Need to See Live",
      "destination_path": "/pokemon/",
      "utm_content": "pin01",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin01",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-02",
      "filename": "pin-02-pokemon.png",
      "category": "pokemon",
      "template": "B",
      "headline": "Pok\u00e9mon Collectors Are Finding These Online",
      "destination_path": "/pokemon/",
      "utm_content": "pin02",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin02",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-03",
      "filename": "pin-03-pokemon.png",
      "category": "pokemon",
      "template": "C",
      "headline": "Where Pok\u00e9mon Collectors Go to Find New Cards",
      "destination_path": "/pokemon/",
      "utm_content": "pin03",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin03",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-04",
      "filename": "pin-04-pokemon.png",
      "category": "pokemon",
      "template": "E",
      "headline": "Live Pok\u00e9mon Card Auctions Explained",
      "destination_path": "/pokemon/",
      "utm_content": "pin04",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin04",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-05",
      "filename": "pin-05-pokemon.png",
      "category": "pokemon",
      "template": "F",
      "headline": "Pok\u00e9mon Finds You Might Not Expect Online",
      "destination_path": "/pokemon/",
      "utm_content": "pin05",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin05",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-06",
      "filename": "pin-06-pokemon.png",
      "category": "pokemon",
      "template": "A",
      "headline": "Pok\u00e9mon Slabs You Might Not Expect to Find Live",
      "destination_path": "/pokemon/",
      "utm_content": "pin06",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin06",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-07",
      "filename": "pin-07-pokemon.png",
      "category": "pokemon",
      "template": "D",
      "headline": "Japanese Pok\u00e9mon Cards Hit Different.",
      "destination_path": "/pokemon/",
      "utm_content": "pin07",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin07",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-08",
      "filename": "pin-08-pokemon.png",
      "category": "pokemon",
      "template": "B",
      "headline": "What Happens in a Live Card Break?",
      "destination_path": "/pokemon/",
      "utm_content": "pin08",
      "destination_url": "https://yourusername.github.io/pokemon/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin08",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-09",
      "filename": "pin-09-sneakers.png",
      "category": "sneakers",
      "template": "A",
      "headline": "Sneaker Finds You Need to See",
      "destination_path": "/sneakers/",
      "utm_content": "pin09",
      "destination_url": "https://yourusername.github.io/sneakers/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin09",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-10",
      "filename": "pin-10-sneakers.png",
      "category": "sneakers",
      "template": "B",
      "headline": "Where Sneaker Collectors Shop Live",
      "destination_path": "/sneakers/",
      "utm_content": "pin10",
      "destination_url": "https://yourusername.github.io/sneakers/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin10",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-11",
      "filename": "pin-11-sneakers.png",
      "category": "sneakers",
      "template": "F",
      "headline": "What Happens When a Live Sneaker Auction Starts at $1?",
      "destination_path": "/sneakers/",
      "utm_content": "pin11",
      "destination_url": "https://yourusername.github.io/sneakers/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin11",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-12",
      "filename": "pin-12-sneakers.png",
      "category": "sneakers",
      "template": "E",
      "headline": "Why Sneakerheads Love Live Shopping",
      "destination_path": "/sneakers/",
      "utm_content": "pin12",
      "destination_url": "https://yourusername.github.io/sneakers/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin12",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-13",
      "filename": "pin-13-sneakers.png",
      "category": "sneakers",
      "template": "C",
      "headline": "Streetwear Finds & Sneaker Drops",
      "destination_path": "/sneakers/",
      "utm_content": "pin13",
      "destination_url": "https://yourusername.github.io/sneakers/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin13",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-14",
      "filename": "pin-14-fashion.png",
      "category": "fashion",
      "template": "A",
      "headline": "The New Way Fashion People Are Shopping",
      "destination_path": "/fashion/",
      "utm_content": "pin14",
      "destination_url": "https://yourusername.github.io/fashion/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin14",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-15",
      "filename": "pin-15-fashion.png",
      "category": "fashion",
      "template": "D",
      "headline": "Luxury Fashion Finds You Can Explore Live",
      "destination_path": "/fashion/",
      "utm_content": "pin15",
      "destination_url": "https://yourusername.github.io/fashion/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin15",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-16",
      "filename": "pin-16-fashion.png",
      "category": "fashion",
      "template": "B",
      "headline": "Fashion Discoveries Hiding in Plain Sight",
      "destination_path": "/fashion/",
      "utm_content": "pin16",
      "destination_url": "https://yourusername.github.io/fashion/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin16",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-17",
      "filename": "pin-17-fashion.png",
      "category": "fashion",
      "template": "E",
      "headline": "Live Shopping for Fashion Lovers",
      "destination_path": "/fashion/",
      "utm_content": "pin17",
      "destination_url": "https://yourusername.github.io/fashion/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin17",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-18",
      "filename": "pin-18-fashion.png",
      "category": "fashion",
      "template": "C",
      "headline": "Y2K & Archive Fashion Discoveries",
      "destination_path": "/fashion/",
      "utm_content": "pin18",
      "destination_url": "https://yourusername.github.io/fashion/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin18",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-19",
      "filename": "pin-19-collectibles.png",
      "category": "collectibles",
      "template": "F",
      "headline": "Labubu & Blind Box Discoveries Live",
      "destination_path": "/collectibles/",
      "utm_content": "pin19",
      "destination_url": "https://yourusername.github.io/collectibles/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin19",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-20",
      "filename": "pin-20-collectibles.png",
      "category": "collectibles",
      "template": "A",
      "headline": "Art Toy Figures & Rare Collectibles",
      "destination_path": "/collectibles/",
      "utm_content": "pin20",
      "destination_url": "https://yourusername.github.io/collectibles/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin20",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-21",
      "filename": "pin-21-collectibles.png",
      "category": "collectibles",
      "template": "B",
      "headline": "Rare Figures & Vaulted Collectibles",
      "destination_path": "/collectibles/",
      "utm_content": "pin21",
      "destination_url": "https://yourusername.github.io/collectibles/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin21",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-22",
      "filename": "pin-22-collectibles.png",
      "category": "collectibles",
      "template": "C",
      "headline": "Anime Statues & Curated Collectibles",
      "destination_path": "/collectibles/",
      "utm_content": "pin22",
      "destination_url": "https://yourusername.github.io/collectibles/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin22",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-23",
      "filename": "pin-23-collectibles.png",
      "category": "collectibles",
      "template": "E",
      "headline": "5 Reasons Collectors Love Live Video Streams",
      "destination_path": "/collectibles/",
      "utm_content": "pin23",
      "destination_url": "https://yourusername.github.io/collectibles/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin23",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-24",
      "filename": "pin-24-beauty.png",
      "category": "beauty",
      "template": "D",
      "headline": "K-Beauty Finds & Live Shade Swatches",
      "destination_path": "/beauty/",
      "utm_content": "pin24",
      "destination_url": "https://yourusername.github.io/beauty/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin24",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-25",
      "filename": "pin-25-beauty.png",
      "category": "beauty",
      "template": "A",
      "headline": "Viral Skincare Products in Action",
      "destination_path": "/beauty/",
      "utm_content": "pin25",
      "destination_url": "https://yourusername.github.io/beauty/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin25",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-26",
      "filename": "pin-26-beauty.png",
      "category": "beauty",
      "template": "F",
      "headline": "Niche Fragrances & Perfume Discoveries",
      "destination_path": "/beauty/",
      "utm_content": "pin26",
      "destination_url": "https://yourusername.github.io/beauty/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin26",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-27",
      "filename": "pin-27-discovery.png",
      "category": "discovery",
      "template": "A",
      "headline": "You Just Found Your New Favorite Way to Shop.",
      "destination_path": "/",
      "utm_content": "pin27",
      "destination_url": "https://yourusername.github.io/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin27",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-28",
      "filename": "pin-28-discovery.png",
      "category": "discovery",
      "template": "B",
      "headline": "What Happens When a Live Auction Starts at $1?",
      "destination_path": "/deals/",
      "utm_content": "pin28",
      "destination_url": "https://yourusername.github.io/deals/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin28",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-29",
      "filename": "pin-29-discovery.png",
      "category": "discovery",
      "template": "E",
      "headline": "5 Things You Won't Believe People Explore Live",
      "destination_path": "/",
      "utm_content": "pin29",
      "destination_url": "https://yourusername.github.io/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin29",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    },
    {
      "pin_id": "PIN-30",
      "filename": "pin-30-discovery.png",
      "category": "discovery",
      "template": "F",
      "headline": "Live Auctions, Whenever You Want to Explore",
      "destination_path": "/",
      "utm_content": "pin30",
      "destination_url": "https://yourusername.github.io/?utm_source=pinterest&utm_medium=organic&utm_campaign=whatnot_referral&utm_content=pin30",
      "status": "READY_TO_POST",
      "created_date": "2026-08-20",
      "published_date": null
    }
  ],
  "nextBatch": [
    {
      "id": "PIN-31",
      "cat": "Pokemon",
      "headline": "5 Secrets Pok\u00e9mon Collectors Look for Live",
      "status": "READY"
    },
    {
      "id": "PIN-32",
      "cat": "Sneakers",
      "headline": "What Sneakerheads Find in Live Stream Auctions",
      "status": "READY"
    },
    {
      "id": "PIN-33",
      "cat": "Fashion",
      "headline": "Vintage Leather & Designer Denim Live",
      "status": "READY"
    },
    {
      "id": "PIN-34",
      "cat": "Collectibles",
      "headline": "Secret Chase Figures & Art Toys Live",
      "status": "READY"
    },
    {
      "id": "PIN-35",
      "cat": "Beauty",
      "headline": "Dewy Glass Skin & Barrier Care Swatches",
      "status": "READY"
    }
  ]
};